#!/bin/sh

UPLINE=$(tput cuu1) # Declare the character that moves up one line
ERASELINE=$(tput el) # Declare the character the erases the line
ERRORS="" 
TESTEDFILES=0
ERRORCOUNT=0
TESTINGSTRING=""

#Runs the initial collection of all failing and passing tests and prints out a summary
PrepCounts() {
  passFiles=(tests/*-pass.kn);
  passFileCount=${#passFiles[@]};
  failFiles=(tests/*-fail.kn);
  failFileCount=${#failFiles[@]};
  totalFiles=$((passFileCount+failFileCount));
  echo "Commencing testing for $passFileCount passing tests and $failFileCount failing tests for $totalFiles total tests.\n";
}

#Prints the current status of tests.
PrintStatus() {
  echo "$ERASELINE$UPLINE$ERASELINE$UPLINE$ERASELINE\c"
  if [ $TESTEDFILES -eq $totalFiles ]
  then
    if [ $ERRORCOUNT -gt 0 ]
    then
      echo "Testing Complete. Errors in $ERRORCOUNT of $TESTEDFILES tests."
    else
      echo "Testing Complete. No Errors."
    fi
  else
    echo "Testing \"$CURRENTFILE\" ($TESTEDFILES of $totalFiles)"
  fi
  echo $TESTINGSTRING
}

#Runs the knode compiler on $CURRENTFILE, sending output to the test's name.log and the file to name.out
TestFile() {
  testname=$(echo $CURRENTFILE | sed -nE 's!tests/(.*)-(pass|fail).kn!\1!p');
  `$(./knode $CURRENTFILE tests/$testname.out >tests/$testname.log 2>&1 )`;
  if [ $? -eq $1 ]
  then
    TESTINGSTRING+="\b\033[32m.\033[0m";
  else
    tmperrors=$(<tests/$testname.log);
    ERRORS="$ERRORS\n\033[34mIn file $CURRENTFILE:\033[0m\n$tmperrors\n";
    ERRORCOUNT=$((ERRORCOUNT+1));
    TESTINGSTRING+="\b\033[31mF\033[0m";
  fi
}


PrepCounts
for file in "${passFiles[@]}"
do
  TESTINGSTRING+="\033[33m.\033[0m"
  CURRENTFILE=$file
  TESTEDFILES=$((TESTEDFILES+1))
  PrintStatus
  TestFile 0
  PrintStatus
done
for file in "${failFiles[@]}"
do
  TESTINGSTRING+="\033[33m.\033[0m"
  CURRENTFILE=$file
  TESTEDFILES=$((TESTEDFILES+1))
  PrintStatus
  TestFile 1
  PrintStatus
done
echo "$ERRORS"
